name: Sync Master with Dev

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge web -> temp-web
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: web
          target_branch: temp-web
          message: Merge web into temp-web
          github_token: ${{ secrets.GITHUB_TOKEN }}