name: Sync Master with Dev

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-branches:
    name: Sync master with dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config --global user.name 'jculajayuniversales'
          git config --global user.email 'jculajay@universales.com'

      - name: Fetch all branches
        run: git fetch --all

      - name: Check if dev branch exists
        id: check-dev
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/temp-web; then
            echo "Dev branch exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Dev branch does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge master into dev
        if: steps.check-dev.outputs.exists == 'true'
        run: |
          git checkout temp-web
          git merge origin/web -m "web into temp-web - Automated sync $(date +%Y-%m-%d)" --allow-unrelated-histories
          git push origin temp-web
        continue-on-error: false