name: CI

on:
  push:
    branches: [ "web" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get commit info
        run: |          
          echo "app=$( $(echo {{github.event.commits[0].message}}) | cut -d" "  -f1)" >> "$GITHUB_ENV"
          for item in ${{ github.event.commits[0].added }}; do
            echo "$file"
          done
          for item in ${{ github.event.commits[0].modified }}; do
            echo "$file"
          done
          echo ${{github.event.ref}}  

      - name: Get files from config folder
        id: dir
        run: echo "name=files::$(ls -m config | sed -r 's/([a-z0-9]+\.ya?ml)/"\1"/gi')" >> $GITHUB_OUTPUT

      - uses: bluwy/substitute-string-action@v1
        with:
          _input-file: 'index.html'
          _output-file: 'index.html'
          _format-key: '%%key%%'
          files: ${{ steps.dir.outputs.files }}

      - name: abc
        run: |
          echo "${{ env.app }}"
