name: CI

on:
  push:
    branches: [ "web" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get commit info
        run: |          
          cat >> "$GITHUB_ENV" << EOF
          app=$(echo "${{github.event.commits[0].message}}" | cut -d'-'  -f1)
          version=$(echo "${{github.event.commits[0].message}}" | cut -d'-'  -f2)
          EOF
                     
          for item in ${{ github.event.commits[0].added }}; do
            echo "$file"
          done
         
          for item in ${{ github.event.commits[0].modified }}; do
            echo "$file"
          done
         
          echo ${{github.event.ref}}  

      - uses: bluwy/substitute-string-action@v1
        id: replace
        with:
          _input-file: 'base-index.html'
          _output-file: 'index.html'
          _format-key: '%%key%%'
          ajustadoresVersion: '1.3.15-26'

      - name: abc
        run: |
          echo "${{ env.app }}"
          echo "${{ steps.replace.outputs.result }}"
          cat index.html
